services:
    App\EventListener\HostSubscriber:
        arguments:
            - '@App\Manager\HostManager'
            - '@App\Certificate\CertificateFactory'
        tags:
            - { name: kernel.event_subscriber }

    App\Twig\TwigExtension:
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: 'twig.extension' }

    App\Certificate\Lescript:
        public: true
        arguments:
          - '%kernel.root_dir%/media/certificate'
          - '@logger'
        calls:
          - ['setContainer', ['@service_container']]

    App\Certificate\CertificateFactory:
        public: true

    App\Controller\NginxController:
        public: true
        arguments:
            - '@view.factory'
            - '@fos_rest.view_handler'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: controller.service_arguments }

    App\Controller\VarnishController:
        public: true
        arguments:
            - '@view.factory'
            - '@fos_rest.view_handler'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: controller.service_arguments }

    App\Viewer\VarnishViewer:
        public: true
        arguments:
            - '@enhavo_app.action_manager'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: 'varnish' }

    App\Viewer\NginxViewer:
        public: true
        arguments:
            - '@enhavo_app.action_manager'
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.viewer, alias: 'nginx' }